# manipulator_control Settings -----------------------

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
   
# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 5

position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
   
# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
joint1_position_controller:
   type: position_controllers/JointPositionController
   joint: joint1
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
   type: position_controllers/JointPositionController
   joint: joint2
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
   type: position_controllers/JointPositionController
   joint: joint3
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint4_position_controller:
   type: position_controllers/JointPositionController
   joint: joint4
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint5_position_controller:
   type: position_controllers/JointPositionController
   joint: joint5
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint6_position_controller:
   type: position_controllers/JointPositionController
   joint: joint6
   pid: {p: 100.0, i: 0.01, d: 10.0}



