// Generated by gencpp from file lnt_ik/lnt_ikResponse.msg
// DO NOT EDIT!


#ifndef LNT_IK_MESSAGE_LNT_IKRESPONSE_H
#define LNT_IK_MESSAGE_LNT_IKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lnt_ik
{
template <class ContainerAllocator>
struct lnt_ikResponse_
{
  typedef lnt_ikResponse_<ContainerAllocator> Type;

  lnt_ikResponse_()
    : result(false)  {
    }
  lnt_ikResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> const> ConstPtr;

}; // struct lnt_ikResponse_

typedef ::lnt_ik::lnt_ikResponse_<std::allocator<void> > lnt_ikResponse;

typedef boost::shared_ptr< ::lnt_ik::lnt_ikResponse > lnt_ikResponsePtr;
typedef boost::shared_ptr< ::lnt_ik::lnt_ikResponse const> lnt_ikResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lnt_ik::lnt_ikResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lnt_ik

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::lnt_ik::lnt_ikResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lnt_ik/lnt_ikResponse";
  }

  static const char* value(const ::lnt_ik::lnt_ikResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::lnt_ik::lnt_ikResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lnt_ikResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lnt_ik::lnt_ikResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lnt_ik::lnt_ikResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LNT_IK_MESSAGE_LNT_IKRESPONSE_H
