// Generated by gencpp from file lnt_ik/lnt_ik.msg
// DO NOT EDIT!


#ifndef LNT_IK_MESSAGE_LNT_IK_H
#define LNT_IK_MESSAGE_LNT_IK_H

#include <ros/service_traits.h>


#include <lnt_ik/lnt_ikRequest.h>
#include <lnt_ik/lnt_ikResponse.h>


namespace lnt_ik
{

struct lnt_ik
{

typedef lnt_ikRequest Request;
typedef lnt_ikResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lnt_ik
} // namespace lnt_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lnt_ik::lnt_ik > {
  static const char* value()
  {
    return "a1a2eac268981f596d714f7568cb7d14";
  }

  static const char* value(const ::lnt_ik::lnt_ik&) { return value(); }
};

template<>
struct DataType< ::lnt_ik::lnt_ik > {
  static const char* value()
  {
    return "lnt_ik/lnt_ik";
  }

  static const char* value(const ::lnt_ik::lnt_ik&) { return value(); }
};


// service_traits::MD5Sum< ::lnt_ik::lnt_ikRequest> should match 
// service_traits::MD5Sum< ::lnt_ik::lnt_ik > 
template<>
struct MD5Sum< ::lnt_ik::lnt_ikRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lnt_ik::lnt_ik >::value();
  }
  static const char* value(const ::lnt_ik::lnt_ikRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lnt_ik::lnt_ikRequest> should match 
// service_traits::DataType< ::lnt_ik::lnt_ik > 
template<>
struct DataType< ::lnt_ik::lnt_ikRequest>
{
  static const char* value()
  {
    return DataType< ::lnt_ik::lnt_ik >::value();
  }
  static const char* value(const ::lnt_ik::lnt_ikRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lnt_ik::lnt_ikResponse> should match 
// service_traits::MD5Sum< ::lnt_ik::lnt_ik > 
template<>
struct MD5Sum< ::lnt_ik::lnt_ikResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lnt_ik::lnt_ik >::value();
  }
  static const char* value(const ::lnt_ik::lnt_ikResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lnt_ik::lnt_ikResponse> should match 
// service_traits::DataType< ::lnt_ik::lnt_ik > 
template<>
struct DataType< ::lnt_ik::lnt_ikResponse>
{
  static const char* value()
  {
    return DataType< ::lnt_ik::lnt_ik >::value();
  }
  static const char* value(const ::lnt_ik::lnt_ikResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LNT_IK_MESSAGE_LNT_IK_H
