// Generated by gencpp from file lnt_ik/lnt_ikRequest.msg
// DO NOT EDIT!


#ifndef LNT_IK_MESSAGE_LNT_IKREQUEST_H
#define LNT_IK_MESSAGE_LNT_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lnt_ik
{
template <class ContainerAllocator>
struct lnt_ikRequest_
{
  typedef lnt_ikRequest_<ContainerAllocator> Type;

  lnt_ikRequest_()
    : values()  {
      values.assign(0.0);
  }
  lnt_ikRequest_(const ContainerAllocator& _alloc)
    : values()  {
  (void)_alloc;
      values.assign(0.0);
  }



   typedef boost::array<float, 6>  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> const> ConstPtr;

}; // struct lnt_ikRequest_

typedef ::lnt_ik::lnt_ikRequest_<std::allocator<void> > lnt_ikRequest;

typedef boost::shared_ptr< ::lnt_ik::lnt_ikRequest > lnt_ikRequestPtr;
typedef boost::shared_ptr< ::lnt_ik::lnt_ikRequest const> lnt_ikRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lnt_ik::lnt_ikRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lnt_ik

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49fffaeb8b23e9b33d73b2dc1dc4f709";
  }

  static const char* value(const ::lnt_ik::lnt_ikRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49fffaeb8b23e9b3ULL;
  static const uint64_t static_value2 = 0x3d73b2dc1dc4f709ULL;
};

template<class ContainerAllocator>
struct DataType< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lnt_ik/lnt_ikRequest";
  }

  static const char* value(const ::lnt_ik::lnt_ikRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] values\n\
";
  }

  static const char* value(const ::lnt_ik::lnt_ikRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lnt_ikRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lnt_ik::lnt_ikRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lnt_ik::lnt_ikRequest_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LNT_IK_MESSAGE_LNT_IKREQUEST_H
